# Generated by Django 5.1.1 on 2024-10-09 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60)),
                ('niche', models.CharField(max_length=60)),
                ('reach', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('profile_picture', models.CharField(default='sample_profile_picture.png', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=360)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.IntegerField(default=0)),
                ('goals', models.CharField(max_length=250)),
                ('influencers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.influencer')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=240)),
                ('influencer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.influencer')),
            ],
        ),
        migrations.CreateModel(
            name='ADRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.CharField(max_length=240)),
                ('payment_amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('status', 'status'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=8)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.campaign')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.influencer')),
                ('messages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.message')),
            ],
        ),
        migrations.AddField(
            model_name='influencer',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.person'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60)),
                ('industry', models.CharField(max_length=60)),
                ('budget', models.IntegerField(default=0)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.person')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.sponsor'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sponsor'),
        ),
    ]
